FROM quay.io/centos/centos:stream9

RUN dnf -y groupinstall "Development Tools"
RUN dnf -y install openssl-devel ncurses-devel libxslt tar git
RUN dnf clean all

RUN curl https://mise.run | sh

WORKDIR /build
